In [1]:
# Importing the basic libraries. 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import pandas_profiling as pdb
import os
plt.style.use('seaborn-darkgrid')

In [2]:
# Loading the data. 查看当前目录下的文件
print(os.listdir('./'))

['.ipynb_checkpoints', 'abalone.csv', 'Abalone.ipynb', 'Ionosphere.ipynb', 'ionosphere_data.csv']

In [3]:
# Loading the data. 
# we will check how good or bad the data is, that we already have. 
data = pd.read_csv('./ionosphere_data.csv')

In [4]:
# checking the data. 
print(data.shape)

(351, 35)

In [5]:
# checking the sample data for data. 
data.head(20)

,column_a,column_b,column_c,column_d,column_e,column_f,column_g,column_h,column_i,column_j,...,column_z,column_aa,column_ab,column_ac,column_ad,column_ae,column_af,column_ag,column_ah,column_ai
0,True,False,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,True,False,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,True,False,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,True,False,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,True,False,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
5,True,False,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,b
6,True,False,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,...,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975,g
7,False,False,0.00000,0.00000,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,...,1.00000,1.00000,1.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,b
8,True,False,0.96355,-0.07198,1.00000,-0.14333,1.00000,-0.21313,1.00000,-0.36174,...,-0.65440,0.57577,-0.69712,0.25435,-0.63919,0.45114,-0.72779,0.38895,-0.73420,g
9,True,False,-0.01864,-0.08459,0.00000,0.00000,0.00000,0.00000,0.11470,-0.26810,...,-0.01326,0.20645,-0.02294,0.00000,0.00000,0.16595,0.24086,-0.08208,0.38065,b
10,True,False,1.00000,0.06655,1.00000,-0.18388,1.00000,-0.27320,1.00000,-0.43107,...,-0.89128,0.47211,-0.86500,0.40303,-0.83675,0.30996,-0.89093,0.22995,-0.89158,g
11,True,False,1.00000,-0.54210,1.00000,-1.00000,1.00000,-1.00000,1.00000,0.36217,...,-0.40888,1.00000,-0.62745,1.00000,-1.00000,1.00000,-1.00000,1.00000,-1.00000,b
12,True,False,1.00000,-0.16316,1.00000,-0.10169,0.99999,-0.15197,1.00000,-0.19277,...,-0.47137,0.76224,-0.58370,0.65723,-0.68794,0.68714,-0.64537,0.64727,-0.67226,g
13,True,False,1.00000,-0.86701,1.00000,0.22280,0.85492,-0.39896,1.00000,-0.12090,...,-0.17012,1.00000,0.35924,1.00000,-0.66494,1.00000,0.88428,1.00000,-0.18826,b
14,True,False,1.00000,0.07380,1.00000,0.03420,1.00000,-0.05563,1.00000,0.08764,...,0.20033,1.00000,0.36743,0.95603,0.48641,1.00000,0.32492,1.00000,0.46712,g
15,True,False,0.50932,-0.93996,1.00000,0.26708,-0.03520,-1.00000,1.00000,-1.00000,...,0.92236,0.39752,0.26501,0.00000,0.00000,1.00000,0.23188,0.00000,0.00000,b
16,True,False,0.99645,0.06468,1.00000,-0.01236,0.97811,0.02498,0.96112,0.02312,...,0.13412,0.79476,0.13638,0.79110,0.15379,0.77122,0.15930,0.70941,0.12015,g
17,False,False,0.00000,0.00000,-1.00000,-1.00000,1.00000,1.00000,-1.00000,1.00000,...,1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,b
18,True,False,0.67065,0.02528,0.66626,0.05031,0.57197,0.18761,0.08776,0.34081,...,0.23724,0.46167,0.24618,0.43433,0.25306,0.40663,0.25792,1.00000,0.33036,g
19,False,False,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,...,1.00000,1.00000,1.00000,1.00000,-1.00000,1.00000,1.00000,1.00000,1.00000,b

In [6]:
# checking basic statistics of data.  统计数据
data.describe()

,column_c,column_d,column_e,column_f,column_g,column_h,column_i,column_j,column_k,column_l,...,column_y,column_z,column_aa,column_ab,column_ac,column_ad,column_ae,column_af,column_ag,column_ah
count,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,0.476183,0.155040,...,0.396135,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480
std,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,0.563496,0.494817,...,0.578451,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,0.021120,-0.065265,...,0.000000,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350
50%,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,0.667980,0.028250,...,0.553890,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000
75%,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,0.957895,0.482375,...,0.905240,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
# Checking the information about the data. 查看非缺失值总数
# this will tell us how many and what type of columns/rows we have in the data. 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   column_a   351 non-null    bool
 1   column_b   351 non-null    bool
 2   column_c   351 non-null    float64
 3   column_d   351 non-null    float64
 4   column_e   351 non-null    float64
 5   column_f   351 non-null    float64
 6   column_g   351 non-null    float64
 7   column_h   351 non-null    float64
 8   column_i   351 non-null    float64
 9   column_j   351 non-null    float64
 10  column_k   351 non-null    float64
 11  column_l   351 non-null    float64
 12  column_m   351 non-null    float64
 13  column_n   351 non-null    float64
 14  column_o   351 non-null    float64
 15  column_p   351 non-null    float64
 16  column_q   351 non-null    float64
 17  column_r   351 non-null    float64
 18  column_s   351 non-null    float64
 19  column_t   351 non-null    float64
 20  column_u   351 non-null    float64
 21  column_v   351 non-null    float64
 22  column_w   351 non-null    float64
 23  column_x   351 non-null    float64
 24  column_y   351 non-null    float64
 25  column_z   351 non-null    float64
 26  column_aa  351 non-null    float64
 27  column_ab  351 non-null    float64
 28  column_ac  351 non-null    float64
 29  column_ad  351 non-null    float64
 30  column_ae  351 non-null    float64
 31  column_af  351 non-null    float64
 32  column_ag  351 non-null    float64
 33  column_ah  351 non-null    float64
 34  column_ai  351 non-null    object
dtypes: bool(2), float64(32), object(1)
memory usage: 91.3+ KB

In [9]:
# Creating a list of columns which are numeric. 
numeric_cols = list(data.select_dtypes(exclude='object').columns)
print(len(numeric_cols))
print(numeric_cols)

34
['column_a', 'column_b', 'column_c', 'column_d', 'column_e', 'column_f', 'column_g', 'column_h', 'column_i', 'column_j', 'column_k', 'column_l', 'column_m', 'column_n', 'column_o', 'column_p', 'column_q', 'column_r', 'column_s', 'column_t', 'column_u', 'column_v', 'column_w', 'column_x', 'column_y', 'column_z', 'column_aa', 'column_ab', 'column_ac', 'column_ad', 'column_ae', 'column_af', 'column_ag', 'column_ah']

In [ ]:
# 为了在生成数据集报告时不引入index索引，故将索引删去
d = data.reset_index(drop=True)

In [ ]:
# using pandas profiler once to look into all the data columns. 
data_profile = pdb.ProfileReport(d)
data_profile